#:schema node_modules/wrangler/config-schema.json
name = "webfinger-handler"
main = "src/index.js" # Ensure this matches your script's path
compatibility_date = "2024-03-25"

# Replace with your actual Cloudflare Account ID
# You can find this in the dashboard sidebar or via 'npx wrangler whoami'
account_id = "d2fe34a62455ac4f2aa2122c2fb524ac"

# The route where your Worker will intercept WebFinger requests
[[routes]]
pattern = "://bridgerfmsaero.com*"
zone_name = "bridgerfmsaero.com"
