name: Deploy Worker
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.cfut_9iG6nuq6aoS0uvHfI2uvuDbK5VVj2ufcfh0TZDWLcc6002a3 }}
          accountId: ${{ secrets.bridgeraerospace-git }}
